# Generated by Django 5.2.17 on 2026-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('roll_number', models.CharField(db_index=True, max_length=30)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveSmallIntegerField()),
                ('division', models.CharField(max_length=30)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='student_profiles/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('student_id',),
                'indexes': [models.Index(fields=['department', 'semester', 'division'], name='students_st_departm_42b596_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx')],
            },
        ),
    ]
