# Generated by Django 5.2.17 on 2026-10-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_mentorassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorAssignment',
        ),
    ]
