# Generated by Django 5.2.17 on 2026-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_mentor_via_faculty'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_departm_42b596_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'semester', 'division', 'batch'], name='students_st_departm_d19625_idx'),
        ),
    ]
