# Generated by Django 5.2.17 on 2026-08-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facedata',
            old_name='embedding',
            new_name='face_embedding',
        ),
        migrations.RenameField(
            model_name='facedata',
            old_name='embedding_model',
            new_name='model_name',
        ),
    ]
