# Generated by Django 5.2.17 on 2026-10-07 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_autoid_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='faculty',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account (Mentor group). Lets this faculty sign in and see their students.', limit_choices_to={'groups__name': 'Mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
