# Generated by Django 5.2.17 on 2026-08-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
        ('faculty', '0002_alter_faculty_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_marked', 'Not Marked')], max_length=15)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_marked', 'Not Marked')], max_length=15)),
                ('reason', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='attendance.attendance')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_modifications', to='faculty.faculty')),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
