# Generated by Django 5.2.17 on 2026-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('computer', 'Computer'), ('ec', 'EC')], max_length=20)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('batch', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('department', 'semester', 'division', 'batch', 'weekday', 'start_time'),
                'indexes': [models.Index(fields=['department', 'semester', 'division', 'batch', 'weekday'], name='timetable_t_departm_1621cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'semester', 'division', 'batch', 'weekday', 'start_time'), name='unique_timetable_slot')],
            },
        ),
    ]
