# Generated by Django 5.2.17 on 2026-10-07 15:12

from django.db import migrations, models


def backfill_batch_end_time(apps, schema_editor):
    TimetableSlot = apps.get_model('timetable', 'TimetableSlot')
    TimetableSlot.objects.filter(batch_end_time__isnull=True).update(batch_end_time=models.F('end_time'))


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='batch_end_time',
            field=models.TimeField(help_text='When the batch session ends. The attendance window below is prefilled around it.', null=True),
        ),
        migrations.RunPython(backfill_batch_end_time, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Prefilled as 10 minutes after the batch end time.', verbose_name='Attendance end time'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Prefilled as 10 minutes before the batch end time.', verbose_name='Attendance start time'),
        ),
    ]
