# Generated by Django 5.2.17 on 2026-08-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('marked_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_marked', 'Not Marked')], default='not_marked', max_length=15)),
                ('recognition_method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('recognition_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ('-attendance_date', 'student__student_id'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_marked', 'Not Marked')], max_length=15)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('not_marked', 'Not Marked')], max_length=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='attendance.attendance')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_modifications', to='faculty.faculty')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'status'], name='attendance__attenda_f3ac94_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_date'), name='unique_student_attendance_per_day'),
        ),
    ]
