# Generated by Django 5.2.17 on 2026-08-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_id_alter_attendancemodification_id'),
        ('faculty', '0002_alter_faculty_designation'),
        ('students', '0002_alter_student_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-date', 'student__student_id')},
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_attendance_per_day',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__attenda_f3ac94_idx',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='marked_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendancemodification',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_modifications', to='attendance.attendance'),
        ),
        migrations.AlterField(
            model_name='attendancemodification',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_attendance_modifications', to='faculty.faculty'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day'),
        ),
    ]
